/*
 * Trello
 * This document describes the REST API of Trello as published by Trello.com.  - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>  - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * MembersBoardBackgrounds
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class MembersBoardBackgrounds {
  public static final String SERIALIZED_NAME_BRIGHTNESS = "brightness";
  @SerializedName(SERIALIZED_NAME_BRIGHTNESS)
  private String brightness;

  public static final String SERIALIZED_NAME_FILE = "file";
  @SerializedName(SERIALIZED_NAME_FILE)
  private String _file;

  public static final String SERIALIZED_NAME_TILE = "tile";
  @SerializedName(SERIALIZED_NAME_TILE)
  private String tile;

  public MembersBoardBackgrounds() {
  }

  public MembersBoardBackgrounds brightness(String brightness) {
    
    
    
    
    this.brightness = brightness;
    return this;
  }

   /**
   * One of: dark, light or unknown
   * @return brightness
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "One of: dark, light or unknown")

  public String getBrightness() {
    return brightness;
  }


  public void setBrightness(String brightness) {
    
    
    
    this.brightness = brightness;
  }


  public MembersBoardBackgrounds _file(String _file) {
    
    
    
    
    this._file = _file;
    return this;
  }

   /**
   * A file
   * @return _file
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A file")

  public String getFile() {
    return _file;
  }


  public void setFile(String _file) {
    
    
    
    this._file = _file;
  }


  public MembersBoardBackgrounds tile(String tile) {
    
    
    
    
    this.tile = tile;
    return this;
  }

   /**
   *  true or false
   * @return tile
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = " true or false")

  public String getTile() {
    return tile;
  }


  public void setTile(String tile) {
    
    
    
    this.tile = tile;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the MembersBoardBackgrounds instance itself
   */
  public MembersBoardBackgrounds putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MembersBoardBackgrounds membersBoardBackgrounds = (MembersBoardBackgrounds) o;
    return Objects.equals(this.brightness, membersBoardBackgrounds.brightness) &&
        Objects.equals(this._file, membersBoardBackgrounds._file) &&
        Objects.equals(this.tile, membersBoardBackgrounds.tile)&&
        Objects.equals(this.additionalProperties, membersBoardBackgrounds.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(brightness, _file, tile, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MembersBoardBackgrounds {\n");
    sb.append("    brightness: ").append(toIndentedString(brightness)).append("\n");
    sb.append("    _file: ").append(toIndentedString(_file)).append("\n");
    sb.append("    tile: ").append(toIndentedString(tile)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("brightness");
    openapiFields.add("file");
    openapiFields.add("tile");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to MembersBoardBackgrounds
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!MembersBoardBackgrounds.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MembersBoardBackgrounds is not found in the empty JSON string", MembersBoardBackgrounds.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("brightness") != null && !jsonObj.get("brightness").isJsonNull()) && !jsonObj.get("brightness").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `brightness` to be a primitive type in the JSON string but got `%s`", jsonObj.get("brightness").toString()));
      }
      if ((jsonObj.get("file") != null && !jsonObj.get("file").isJsonNull()) && !jsonObj.get("file").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `file` to be a primitive type in the JSON string but got `%s`", jsonObj.get("file").toString()));
      }
      if ((jsonObj.get("tile") != null && !jsonObj.get("tile").isJsonNull()) && !jsonObj.get("tile").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tile` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tile").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MembersBoardBackgrounds.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MembersBoardBackgrounds' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MembersBoardBackgrounds> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MembersBoardBackgrounds.class));

       return (TypeAdapter<T>) new TypeAdapter<MembersBoardBackgrounds>() {
           @Override
           public void write(JsonWriter out, MembersBoardBackgrounds value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public MembersBoardBackgrounds read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             MembersBoardBackgrounds instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of MembersBoardBackgrounds given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of MembersBoardBackgrounds
  * @throws IOException if the JSON string is invalid with respect to MembersBoardBackgrounds
  */
  public static MembersBoardBackgrounds fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MembersBoardBackgrounds.class);
  }

 /**
  * Convert an instance of MembersBoardBackgrounds to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

